### ISSUE TITLE
About the code of 'label propagation'

### ISSUE THREAD

**Issue by yl255** [YaoZhang93/Semi-supervised-Cardiac-Image-Segmentation-via-Label-Propagation-and-Style-Transfer#1]
Hi,
I read your great work.
In section 3.2, you said, 'we use ANTs as the implementation of label propagation algorithm...'
But I can not find the code of doing that.
Would you mind to provide the code of the "LP"?
Thanks for your great work!
best,
Yaliang

**Comment by YaoZhang93** [comment]
Hi Yaliang,

Thanks for your interest.The code has already been included [here](https://github.com/YaoZhang93/Semi-supervised-Cardiac-Image-Segmentation-via-Label-Propagation-and-Style-Transfer/blob/main/Data_Preprocess/register.sh).

Best,
Yao

**Comment by yl255** [comment]
> Hi Yaliang,
> 
> Thanks for your interest.The code has already been included [here](https://github.com/YaoZhang93/Semi-supervised-Cardiac-Image-Segmentation-via-Label-Propagation-and-Style-Transfer/blob/main/Data_Preprocess/register.sh).
> 
> Best, Yao

Thanks!
